/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as quorumTokenBackupSol from "./QuorumToken.backup.sol";
export type { quorumTokenBackupSol };
export type { TicketNFT } from "./TicketNFT";
